key mod
Thesola10/osu-DIVA pull request #27
Opened 2021-04-08 13:50 UTC by Artemis-chan

fixes part 1 of #4, backported from osu mania as suggested by @Thesola10

2021-04-08 13:52 UTC, Thesola10 commented
wonder if there's a way to use custom graphics as mod icons

2021-04-08 13:55 UTC, Thesola10 requested changes

2021-04-08 13:55 UTC, Thesola10 commented on osu.Game.Rulesets.Diva/Mods/DivaModKey3.cs
> +		public override string Name => "3 Button";
should be "Three Button" for consistency

Actually make Button plural on all ModKey as well?

2021-04-08 13:55 UTC, Thesola10 commented
No functional problems upon testing tho

2021-04-08 14:05 UTC, Thesola10 approved these changes
naisu

2021-04-08 14:06 UTC, merged

2021-04-11 08:48 UTC, Artemis-chan commented
> 
> 
> wonder if there's a way to use custom graphics as mod icons

It seems like they are using customs fonts  for the custom mod graphics ([source](https://github.com/ppy/osu/blob/ab49e84d170cf7376ca25e6f239306ccf840475a/osu.Game/Graphics/OsuIcon.cs#L8)).

2021-04-11 10:49 UTC, Thesola10 commented
Doesn't that mean we can introduce our own font (it's some compiled PNG table) and use that for mod icons?

2021-04-11 11:16 UTC, Artemis-chan commented
i have looked into it, ([this is how the framework loads](https://github.com/ppy/osu-framework/blob/51c96583c08a6167a7048c6486604f6a5f5a966f/osu.Framework/Game.cs#L209))
I think if we use the background dependency loader to inject OsuGame(Base?) and add the font using `AddFont()`